### ISSUE TITLE
Eu151Di seems to be CD25, not a bead marker

### ISSUE THREAD

**Issue by LTLA** [MarioniLab/SingleCellAPL2018#4]
Your comments on line 57 of `cytof/analysis.Rmd` suggest that the beads are both Eu151 and Eu153. But the annotation within the file indicates that the Eu151 is CD25, and the code only actually filters on Eu153.

**Comment by ACRichard** [comment]
Both could have been used to gate as double-positive events should have been beads, but only Eu153 was used in the end. Sorry for the confusion in the comment - this has been clarified.
